### ISSUE TITLE
TCP timeout handling

### ISSUE THREAD

**Issue by oviano** [paullouisageneau/libplum#23]
I found that the UPnP protocol was occasionally failing due to a TCP timeout receiving an HTTP response.

This seems to be treated as a fatal error and propagates back up the call tree as a protocol failed, and so doesn't get tried again.

I believe this to be incorrect - if the UPnP protocol code has got as far as receiving a UDP response containing the location URL then a timeout during http get/post should not be fatal but instead part of the regular retrying process of the protocol where it has an overall timeout of 5000ms and 20 (or something) attempts.

**Comment by paullouisageneau** [comment]
HTTP timeout errors are indeed propagated as generic errors and the protocol fails, while it would make sense to retry until timeout.

**Comment by oviano** [comment]
https://github.com/paullouisageneau/libplum/pull/30
